#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-16 16:40:55.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("response_to_data_frame_raw() works", {

  f <- kwb.dwd:::response_to_data_frame_raw

  expect_error(
    f()
    # argument "response" is missing, with no default
  )

})
