#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-16 16:43:25.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("read_asc_gz_file_into_matrix() works", {

  f <- kwb.dwd:::read_asc_gz_file_into_matrix

  expect_error(
    f()
    # argument "url" is missing, with no default
  )

})
