#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-16 16:40:55.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("main_columns_first() works", {

  f <- kwb.dwd:::main_columns_first

  expect_error(
    f()
    # argument "df" is missing, with no default
  )

})
