#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-16 16:43:25.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("download_if_not_there() works", {

  f <- kwb.dwd:::download_if_not_there

  expect_error(
    f()
    # argument "url" is missing, with no default
  )

})
