#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-16 16:40:55.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("empty_file_info() works", {

  f <- kwb.dwd:::empty_file_info

  result <- f()

  expect_s3_class(result, "data.frame")
  expect_identical(nrow(result), 0L)
  expect_true(all(c("file", "isdir", "size") %in% names(result)))
})
