#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-16 16:40:55.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("columns_to_timestamp() works", {

  f <- kwb.dwd:::columns_to_timestamp

  expect_error(
    f()
    # argument "info" is missing, with no default
  )

})
