#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-16 16:40:56.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("calculate_masked_grid_stats() works", {

  f <- kwb.dwd:::calculate_masked_grid_stats

  expect_error(
    kwb.dwd:::calculate_masked_grid_stats()
    # argument "matrices" is missing, with no default
  )

})
