#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-16 16:43:28.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("try_to_get_url() works", {

  f <- kwb.dwd:::try_to_get_url

  expect_error(
    f()
    # argument "url" is missing, with no default
  )

})
