#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-16 16:43:30.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("month_sequence() works", {

  f <- kwb.dwd:::month_sequence

  expect_error(
    f()
    # argument "start" is missing, with no default
  )

})
