#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-16 16:43:24.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("provide_projection_file() works", {

  f <- kwb.dwd:::provide_projection_file

  expect_error(
    f()
    # argument "file" is missing, with no default
  )

})
