#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-16 16:40:06.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("dwd_url_climate_dir() works", {

  f <- kwb.dwd:::dwd_url_climate_dir

  result <- f()

  expect_length(result, 1L)
  expect_type(result, "character")
  expect_true(startsWith(result, "ftp://"))

  result2 <- f("daily")

  expect_error(f("no-such-frequency"))
  expect_error(f("daily", category = "no-such-category"))
})
