#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-16 16:43:24.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("open_description() works", {

  f <- kwb.dwd:::open_description

  expect_error(
    kwb.dwd:::open_description()
    # argument "url" is missing, with no default
  )

})
