#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-16 16:43:30.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("filter_by_month_range() works", {

  f <- kwb.dwd:::filter_by_month_range

  expect_error(
    f()
    # argument "urls" is missing, with no default
  )

})
