#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-20 04:44:47.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("extract_metadata_from_files() works", {

  f <- kwb.dwd:::extract_metadata_from_files

  expect_error(
    f()
    # argument "files" is missing, with no default
  )

})
