#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-16 16:43:30.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("list_monthly_grids_germany_asc_gz() works", {

  f <- kwb.dwd:::list_monthly_grids_germany_asc_gz

  expect_error(
    f()
    # argument "variable" is missing, with no default
  )

})
