#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-16 16:43:27.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("read_relevant_years_radolan() works", {

  f <- kwb.dwd:::read_relevant_years_radolan

  expect_error(
    kwb.dwd:::read_relevant_years_radolan()
    # argument "years" is missing, with no default
  )

})
