#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-16 16:40:06.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("dwd_filename_stations() works", {

  f <- kwb.dwd:::dwd_filename_stations

  expect_error(
    f()
    # argument "category" is missing, with no default
  )

})
