#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-16 16:40:54.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("list_local_shape_files() works", {

  f <- kwb.dwd:::list_local_shape_files

  expect_error(
    f()
    # argument "path" is missing, with no default
  )

})
