#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-16 16:40:09.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_radolan_url() works", {

  f <- kwb.dwd:::get_radolan_url

  expect_error(
    f()
    # argument "frequency" is missing, with no default
  )

})
