#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-16 16:40:08.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("to_projection_string() works", {

  f <- kwb.dwd:::to_projection_string

  expect_error(
    f()
    # argument "parameters" is missing, with no default
  )

})
