#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-16 16:40:56.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_file_metadata_from_attributes() works", {

  f <- kwb.dwd:::get_file_metadata_from_attributes

  expect_error(
    f()
    # argument "x" is missing, with no default
  )

})
