#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-16 16:43:30.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("extract_yyyymm() works", {

  f <- kwb.dwd:::extract_yyyymm

  expect_error(
    f()
    # argument "x" is missing, with no default
  )

})
