#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-20 04:44:46.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("read_esri_ascii_grid_lines_into_matrix() works", {

  f <- kwb.dwd:::read_esri_ascii_grid_lines_into_matrix

  expect_error(
    f()
    # argument "text" is missing, with no default
  )

})
