#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-09-16 16:43:24.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("find_description_files() works", {

  f <- kwb.dwd:::find_description_files

  expect_error(
    f()
    # argument "url" is missing, with no default
  )

})
